#Reema Maryam Naheem 397000990
spring.application.name=Reel_n_Roll
spring.datasource.url=jdbc:mysql://localhost:3307/iste240?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update


spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:sql/ShowtimeRecords.sql



